name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env: 
      SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
      TOKEN: ${{ secrets.TOKEN }}
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull submodules
      run: git submodule update --init --recursive --depth 1    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          8.0.x
          9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - uses: "authzed/action-spicedb@v1"
      with:
        version: "latest"       
    - name: Test
      run: dotnet test --verbosity normal
    - name: Publish  
      uses: brandedoutcast/publish-nuget@v2.5.2  
      with:   
       PROJECT_FILE_PATH: SpiceDb/SpiceDb.csproj  
       NUGET_KEY: ${{secrets.NUGET_API_KEY}}  